# Generated by Django 5.2.11 on 2026-02-18 11:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(default='misc.png', help_text='Icon filename from assets/icons/', max_length=50)),
                ('color_hex', models.CharField(default='#6C5CE7', max_length=7)),
                ('is_default', models.BooleanField(default=False, help_text="System-provided category that can't be deleted")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='NULL = system default category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'Parents', 'Part-time job'", max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('one_time', 'One Time'), ('weekly', 'Weekly'), ('bi_monthly', 'Bi-Monthly'), ('monthly', 'Monthly')], max_length=20)),
                ('next_expected', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'income_sources',
            },
        ),
        migrations.CreateModel(
            name='RecurringPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern_title', models.CharField(max_length=200)),
                ('avg_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('occurrence_count', models.IntegerField(default=0)),
                ('first_seen', models.DateField()),
                ('last_seen', models.DateField()),
                ('user_acknowledged', models.BooleanField(default=False, help_text='User has seen and confirmed this pattern')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recurring_patterns',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive. Type field determines expense vs income.', max_digits=12)),
                ('transaction_date', models.DateField()),
                ('auto_category', models.CharField(blank=True, choices=[('minor', 'Minor Expense'), ('major', 'Major Expense'), ('minor_repetitive', 'Minor Repetitive')], help_text='ML-assigned magnitude classification', max_length=20, null=True)),
                ('category_confidence', models.FloatField(blank=True, help_text='ML model confidence (0.0 to 1.0)', null=True)),
                ('is_synced', models.BooleanField(default=True, help_text='False if created offline and not yet confirmed by server')),
                ('device_id', models.CharField(blank=True, default='', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_category_per_user'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-transaction_date'], name='idx_txn_user_date'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category'], name='idx_txn_user_category'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'type'], name='idx_txn_user_type'),
        ),
    ]
