# Generated by Django 5.2.11 on 2026-02-18 11:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='created, updated, deleted', max_length=20)),
                ('entity_type', models.CharField(help_text='Model name: transaction, budget, savings_goal, etc.', max_length=50)),
                ('entity_id', models.UUIDField(help_text='PK of the affected record')),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_audit_user_time')],
            },
        ),
        migrations.CreateModel(
            name='DeviceSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=100)),
                ('device_name', models.CharField(blank=True, default='', max_length=200)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('pending_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_syncs',
                'constraints': [models.UniqueConstraint(fields=('user', 'device_id'), name='unique_device_per_user')],
            },
        ),
    ]
